export default [{
  'name': 'EOS Bet Casino',
  'description': 'The largest casino and gaming platform on the powerful EOS blockchain. We offer fully feeless, trustless and provably fair games. 100% of EOS earned on the platform is returned to holders of our BET token.',
  'symbol': 'BET',
  'accounts': ['eosbetdice11', 'eosbetcasino', 'betdividends'],
  'logo': 'https://raw.githubusercontent.com/eoscafe/eos-dapps/master/logos/eosbet.png',
  'website': 'https://www.eosbet.io/',
  'app': 'https://www.dice.eosbet.io',
  'telegram': 'https://t.me/eosbetcasino',
  'medium': '',
  'twitter': '',
  'github': ''
},
{
  'name': 'EOS Knights',
  'description': 'An idle RPG on iOS and Android set to be the earliest live implementations of the EOS blockchain in a game.',
  'symbol': '',
  'accounts': ['eosknightsio'],
  'logo': 'https://raw.githubusercontent.com/eoscafe/eos-dapps/master/logos/eosknights.png',
  'website': 'https://eosknights.io',
  'app': 'http://game.eosknights.io',
  'telegram': 'https://t.me/joinchat/IAL3EwvtSVMml_qkYPXbrw',
  'medium': '',
  'twitter': '',
  'github': ''
},
{
  'name': 'Everipedia',
  'description': 'The Everipedia team plans to build a modern, convenient and decentralized new encyclopedia website, and this goal will be realized with the development of blockchain technology. The new version of Everipedia under development will be based on the EOS network, which will have features such as community autonomy, shielding preventation, and contribution incentives compared to the current version of Everipedia. Founded in 2014, the business network encyclopedia Everipedia, whose name derives from the English words Everything and Encyclopedia, is owned by Everipedia.Inc and has not yet adopted blockchain technology. As of December 2017, Everipedia is the largest English encyclopedia with more than six million entries, including all English entries of Wikipedia. Everipedias requirements for attention are more relaxed, so it has more entries than Wikipedia.',
  'symbol': 'IQ',
  'accounts': ['everipediaiq', 'eparticlectr'],
  'logo': 'https://raw.githubusercontent.com/eoscafe/eos-dapps/master/logos/everipedia.png',
  'website': '',
  'app': 'https://everipedia.org',
  'telegram': 'https://t.me/everipedia',
  'medium': '',
  'twitter': '',
  'github': ''
},
{
  'name': 'EOSPlay Lottery & Dice',
  'description': 'EOSPLAY is a revolutionary game center in which players bet against externally generated EOS main net hash, guarantees instant betting, absolute fairness and transparency.',
  'symbol': '',
  'accounts': ['eosplaybrand'],
  'logo': 'https://raw.githubusercontent.com/eoscafe/eos-dapps/master/logos/eospick.png',
  'website': '',
  'app': 'https://eosplay.co/',
  'telegram': 'https://t.me/eosplay',
  'medium': '',
  'twitter': '',
  'github': ''
},
{
  'name': 'eosDAC',
  'description': 'eosDAC is a Community Owned Blockproducer and a DAC enabler, born out of Dan Larimers concept of Decentralized Autonomous Communities or DACs, around which Block.one developed EOS software.  The vision of eosDAC is that EOS.IO block production should be open for everyone to contribute and benefit. To realize this vision, eosDAC is an evolving Decentralised Autonomous Community (DAC) focused on EOS.IO Block Production serving the EOS communities worldwide. In doing this, eosDAC is creating the tools and smart contracts it needs to function. It will share these with the EOS communities to help other DACs thrive on the EOS.IO blockchains.  In order to function as a DAC, eosDAC is creating open source tools and will be sharing them as a DAC Toolkit, that anyone can use, modify to setup and run a DAC.',
  'symbol': 'EOSDAC',
  'accounts': ['eosdactokens', 'eosdacserver', 'eosdacthedac', 'daccustodian'],
  'logo': 'https://raw.githubusercontent.com/eoscafe/eos-dapps/master/logos/eosdac.png',
  'website': '',
  'app': 'https://eosdac.io',
  'telegram': 'https://t.me/eosdacio',
  'medium': '',
  'twitter': '',
  'github': 'https://github.com/eosdac'
},
{
  'name': 'DEOS Games',
  'description': 'Deos Games are casino games built on EOS blockchain. Play zero edge games with our DEOS token and participate in bankroll staking.',
  'symbol': 'DEOS',
  'accounts': ['thedeosgames', 'deosgameissu'],
  'logo': 'https://raw.githubusercontent.com/eoscafe/eos-dapps/master/logos/deosgames.png',
  'website': 'https://deosgames.com',
  'app': 'https://app.deosgames.com',
  'telegram': 'https://t.me/deosgameschat',
  'medium': 'https://medium.com/deos-games',
  'twitter': '',
  'github': ''
},
{
  'name': 'BetDice',
  'description': 'BetDice is the largest gaming platform on EOS blockchain. Users can earn DICE tokens from playing, and then get dividends from staking. Both the platform and the token are based on user-centered design, which giving our users the best gaming experience.',
  'symbol': 'DICE',
  'accounts': [
    'betdiceadmin',
    'betdicealert',
    'betdicegiver',
    'betdicegroup',
    'betdicehouse',
    'betdicelucky',
    'betdicelotto',
    'betdicesales',
    'betdiceshare',
    'betdicesaver',
    'betdicestake',
    'betdicetoken',
    'betdiceusers'
  ],
  'logo': 'https://raw.githubusercontent.com/eoscafe/eos-dapps/master/logos/betdice.jpg',
  'website': '',
  'app': 'https://betdice.one',
  'telegram': 'https://t.me/betdice',
  'medium': 'https://medium.com/@betdice',
  'twitter': 'https://twitter.com/bet_dice',
  'github': ''
},
{
  'name': 'Chintai',
  'description': 'Chintai is a Singapore-based SaaS company that modernizes capital markets infrastructure with blockchain technology. Chintai is building a regulated platform that offers comprehensive digital asset services for primary issuance, secondary markets, and asset management.',
  'symbol': 'CHEX',
  'accounts': ['chintaiproxy', 'chexchexchex'],
  'logo': 'https://chintai.io/images/chintai-icon.png',
  'website': 'https://chintai.io',
  'app': '',
  'telegram': 'https://t.me/ChintaiNetwork',
  'medium': '',
  'twitter': 'https://twitter.com/ChintaiNetwork',
  'github': 'https://github.com/chintai-platform'
},
{
  'name': 'EOS Name Swaps',
  'description': 'An open-source EOS account exchange that puts the security of its users first.',
  'symbol': '',
  'accounts': ['eosnameswaps'],
  'logo': 'https://www.eosnameswaps.com/images/ens_logo.jpg',
  'website': 'https://www.eosnameswaps.com/?ref=bloks',
  'app': 'https://www.eosnameswaps.com/?ref=bloks',
  'telegram': 'https://t.me/eosnameswaps',
  'medium': '',
  'twitter': 'https://twitter.com/Starry3017Night',
  'github': 'https://github.com/StarryJapanNight/eosnameswaps'
}]
